-->Task1
drop table MyTable;
Create table MyTable(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	val NUMBER,
    PRIMARY KEY(id)
);

-->Task2
declare
    l_random_val NUMBER;
begin
    l_random_val:=dbms_random.random;
	for i in 1..99 loop
		insert into MyTable(val) values (l_random_val);
	end loop;
end;
/

SELECT * from MyTable;

-->Task3

